version: "3"


services:
#  webapp:
#    build: backend/Dockerfile
##    environment:
##      - NODE_ENV = development
#    ports:
#    - 8080:8080
#
#    links:
#      - database
#    depends_on:
#      - database
## проблемы с монгой
#  database:
#    image: mongo:latest
#    container_name: "mongodb"
##   environment:
##     - MONGO_DATA_DIR=/data/db
##     - MONGO_LOG_DIR=/dev/null
#    ports:
#    - 27017:27017
#    command: mongod

  frontend:
    container_name: vue_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'

