version: "3"

services:
  backend:
    build:
      context:  ./backend
      dockerfile: Dockerfile
    container_name: node_app
    volumes:
      - './backend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
    - 8999:8999
    - 3000:3000
    depends_on:
      - mongo
    restart: always

## проблемы с монгой
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
    - 27017:27017

  frontend:
    container_name: vue_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend

